name: Deploy Lambda with Terraform

on:
  push:
    branches:
      - main

jobs:
  terraform:
    name: "Terraform Apply"
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1

      - name: Initialize Terraform
        run: |
          terraform init

      - name: Plan Terraform Changes
        run: |
          terraform plan -out=tfplan

      - name: Apply Terraform Changes
        run: |
          terraform apply -auto-approve tfplan

  deploy_lambda:
    name: "Deploy Lambda Function"
    runs-on: ubuntu-latest
    needs: terraform

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt -t .
          zip -r lambda_function.zip .

      - name: Upload Lambda Code
        run: |
          aws lambda update-function-code \
            --function-name S3BucketTriggerLambda \
            --zip-file fileb://lambda/lambda_function.zip
